-- =====================================================
-- Prompt Lab 초기 시드 데이터
-- =====================================================

-- 1. Modules 시드 데이터
INSERT INTO modules (id, title, title_en, description, description_en, techniques, policy_context, order_index, prerequisite_module_id) VALUES
('11111111-1111-1111-1111-111111111111',
 '좋은 질문이 좋은 답을 만든다',
 'Good Questions Make Good Answers',
 '프롬프트가 AI 응답 품질에 미치는 영향을 체험적으로 이해합니다. 단계별 사고를 유도하여 복잡한 문제를 해결하는 방법을 배웁니다.',
 'Understand experientially how prompts affect AI response quality. Learn to guide step-by-step thinking to solve complex problems.',
 ARRAY['Chain of Thought'],
 '정책 이슈 질문',
 1,
 NULL),

('22222222-2222-2222-2222-222222222222',
 '문헌 리뷰 효과적으로 하기',
 'Effective Literature Review',
 '학술 문헌 검색, 요약, 정리에 효과적인 프롬프트 작성법을 배웁니다. 예시를 통한 패턴 학습과 출력 구조화 기법을 익힙니다.',
 'Learn effective prompt writing for academic literature search, summarization, and organization. Master pattern learning through examples and output structuring.',
 ARRAY['Few-shot Learning', 'Output Structuring'],
 '캡스톤 선행연구',
 2,
 '11111111-1111-1111-1111-111111111111'),

('33333333-3333-3333-3333-333333333333',
 '정책 비교 분석 요청하기',
 'Policy Comparison Analysis',
 '국가 간/정책 간 비교 분석을 위한 구조화된 프롬프트 작성법을 배웁니다. 체계적 분석과 다관점 검토 기법을 익힙니다.',
 'Learn structured prompt writing for cross-country/policy comparative analysis. Master systematic analysis and multi-perspective review techniques.',
 ARRAY['Chain of Thought', 'Output Structuring', 'Self-Consistency'],
 '국가 간 정책 비교',
 3,
 '22222222-2222-2222-2222-222222222222'),

('44444444-4444-4444-4444-444444444444',
 '데이터 해석 도움받기',
 'Getting Help with Data Interpretation',
 '통계 데이터 해석, 시각화 제안, 분석 방향 설정에 AI를 활용하는 방법을 배웁니다. 전문가 페르소나 설정과 단계별 분석 기법을 익힙니다.',
 'Learn to use AI for statistical data interpretation, visualization suggestions, and analysis direction setting. Master expert persona setting and step-by-step analysis.',
 ARRAY['Persona', 'Chain of Thought', 'Few-shot Learning'],
 '통계/회귀분석 해석',
 4,
 '33333333-3333-3333-3333-333333333333'),

('55555555-5555-5555-5555-555555555555',
 '정책 문서 작성 지원받기',
 'Policy Document Writing Support',
 '브리핑, 정책 메모, 제안서 등 실무 문서 작성에 AI를 활용하는 방법을 배웁니다. 지금까지 배운 모든 테크닉을 종합적으로 적용합니다.',
 'Learn to use AI for writing practical documents like briefings, policy memos, and proposals. Apply all techniques learned comprehensively.',
 ARRAY['Persona', 'Few-shot Learning', 'Constraints'],
 '브리핑/메모/제안서',
 5,
 '44444444-4444-4444-4444-444444444444');

-- 2. Scenarios 시드 데이터
INSERT INTO scenarios (module_id, category, title, title_en, context, context_en, base_prompt_example, improved_prompt_example, comparison_criteria) VALUES
-- Module 1 시나리오
('11111111-1111-1111-1111-111111111111',
 'policy_comparison',
 '개발도상국 UBI 정책 분석',
 'UBI Policy Analysis in Developing Countries',
 '당신은 "개발도상국의 보편적 기본소득(UBI) 정책"에 대해 알아보려고 합니다. AI에게 어떻게 질문하시겠습니까?',
 'You want to learn about "Universal Basic Income (UBI) policies in developing countries". How would you ask AI?',
 'UBI에 대해 알려줘',
 '개발도상국에서 UBI 정책을 도입할 때 고려해야 할 사항을 단계별로 분석해주세요: (1) 먼저 재정적 실현가능성을 검토하고, (2) 기존 사회보장제도와의 관계를 분석하고, (3) 정치적 수용성을 평가하고, (4) 최종적으로 정책 제언을 도출해주세요.',
 '{"specificity": "구체적인 분석 단계 제시 여부", "context": "개발도상국 맥락 명시 여부", "structure": "논리적 순서 제시 여부"}'),

-- Module 2 시나리오
('22222222-2222-2222-2222-222222222222',
 'literature_review',
 '기후변화와 농업 정책 문헌 리뷰',
 'Climate Change and Agricultural Policy Literature Review',
 '캡스톤 프로젝트를 위해 "기후변화가 동남아시아 농업 정책에 미친 영향"에 대한 문헌 리뷰를 시작하려 합니다. AI에게 어떻게 도움을 요청하시겠습니까?',
 'You are starting a literature review on "the impact of climate change on agricultural policies in Southeast Asia" for your capstone project. How would you ask AI for help?',
 '기후변화와 농업 정책 논문 요약해줘',
 '아래 형식에 맞춰 논문들을 요약해주세요.\n\n**[예시]**\n• 저자/연도: Smith et al. (2020)\n• 연구 질문: 탄소세가 농가 소득에 미치는 영향\n• 방법론: 패널 데이터 분석 (2010-2019)\n• 핵심 발견: 탄소세 1% 인상 시 농가 소득 0.3% 감소\n• 정책 함의: 농가 보조금 병행 필요\n\n이 형식으로 기후변화가 동남아시아 농업 정책에 미친 영향 관련 주요 연구 5개를 정리해주세요.',
 '{"examples": "예시 형식 제공 여부", "structure": "출력 구조 명시 여부", "specificity": "구체적 요청 사항 포함 여부"}'),

-- Module 3 시나리오
('33333333-3333-3333-3333-333333333333',
 'policy_comparison',
 '한국-독일 재생에너지 정책 비교',
 'Korea-Germany Renewable Energy Policy Comparison',
 'Policy Analysis 수업 과제로 "한국과 독일의 재생에너지 정책"을 비교해야 합니다. AI에게 어떻게 분석을 요청하시겠습니까?',
 'For your Policy Analysis class assignment, you need to compare "renewable energy policies of Korea and Germany". How would you ask AI for analysis?',
 '한국이랑 독일 재생에너지 정책 비교해줘',
 '한국과 독일의 재생에너지 정책을 비교 분석해주세요.\n\n**분석 순서:**\n1단계: 각 국가의 정책 배경과 목표를 먼저 정리\n2단계: 정책 수단을 범주별로 비교 (규제, 인센티브, R&D)\n3단계: 성과 지표로 효과성 평가\n4단계: 각 정책의 강점과 약점 도출\n5단계: 한국 관점에서 시사점 정리\n\n마지막에 **반대 관점**도 검토해주세요: 독일 모델을 한국에 적용하기 어려운 이유는 무엇일까요?',
 '{"structure": "분석 단계 명시 여부", "criteria": "비교 기준 제시 여부", "multi_perspective": "반대 관점 요청 여부"}'),

-- Module 4 시나리오
('44444444-4444-4444-4444-444444444444',
 'data_analysis',
 'ODA와 교육 성과 회귀분석 해석',
 'ODA and Education Outcomes Regression Analysis',
 'World Bank 데이터로 "ODA가 수원국 교육 성과에 미친 영향"을 분석하고 있습니다. 회귀분석 결과가 나왔는데 해석에 어려움을 겪고 있습니다. AI에게 어떻게 도움을 요청하시겠습니까?',
 'You are analyzing "the impact of ODA on recipient country education outcomes" using World Bank data. You have regression results but are having difficulty interpreting them. How would you ask AI for help?',
 '이 회귀분석 결과 해석해줘 [데이터]',
 '**당신은 World Bank에서 10년간 개발도상국 교육 정책을 연구한 개발경제학자입니다. 데이터 기반 분석을 중시하며, 정책 입안자가 이해할 수 있는 언어로 설명합니다.**\n\n아래 회귀분석 결과를 해석해주세요.\n[데이터]\n\n**해석 형식 예시:**\n''ODA 변수의 계수 0.15는 ODA가 1% 증가할 때 취학률이 0.15%p 상승함을 의미하며, p-value 0.03으로 5% 유의수준에서 통계적으로 유의하다.''\n\n위 형식을 참고하여 **단계별로** 분석해주세요:\n1. 각 변수의 계수와 유의성 해석\n2. 모델 전체의 설명력 평가\n3. 잠재적 한계점 (내생성, 누락변수 등)\n4. 정책적 함의',
 '{"persona": "전문가 페르소나 설정 여부", "examples": "해석 예시 제공 여부", "structure": "단계별 분석 요청 여부"}'),

-- Module 5 시나리오
('55555555-5555-5555-5555-555555555555',
 'policy_document',
 '저출산 대응 정책 브리핑',
 'Low Fertility Policy Briefing',
 'KDI에서 인턴 중입니다. 부장님이 "한국 저출산 대응 정책 현황"에 대한 2페이지 브리핑 자료를 내일까지 요청하셨습니다. AI에게 어떻게 초안 작성을 요청하시겠습니까?',
 'You are interning at KDI. Your director has requested a 2-page briefing on "current Korean low fertility response policies" by tomorrow. How would you ask AI to help draft it?',
 '한국 저출산 정책 브리핑 써줘',
 '**독자:** KDI 정책연구 부장 (경제학 박사, 바쁜 일정)\n**목적:** 내일 장관 보고 전 현황 파악\n\n**좋은 브리핑 문장 예시:**\n''2023년 합계출산율 0.72명으로 OECD 최저 수준이며, 이는 전년 대비 8% 하락한 수치임.''\n\n위 스타일로 한국 저출산 대응 정책 현황 브리핑을 작성해주세요.\n\n**제약조건:**\n• 분량: 2페이지 이내\n• 톤: 간결하고 객관적\n• 구성: 현황 → 주요 정책 → 쟁점 → 향후 과제\n• 통계는 출처 표기 필요 (없으면 [출처 확인 필요]로 표시)',
 '{"audience": "독자 명시 여부", "examples": "문체 예시 제공 여부", "constraints": "제약조건 명시 여부", "structure": "구성 요청 여부"}');

-- 3. Socratic Question Templates 시드 데이터
-- Module 1: Chain of Thought
INSERT INTO socratic_question_templates (module_id, question_type, question_text, question_text_en, purpose, order_index) VALUES
('11111111-1111-1111-1111-111111111111', 'exploration',
 '교수님께 질문할 때와 AI에게 질문할 때, 어떤 점이 비슷하고 다를까요?',
 'What similarities and differences do you see between asking a question to a professor versus asking AI?',
 '기존 지식 및 경험 확인', 1),
('11111111-1111-1111-1111-111111111111', 'exploration',
 '같은 주제에 대해 모호하게 질문하면 어떤 답을 받을 것 같나요?',
 'What kind of answer do you think you would get if you ask vaguely about the same topic?',
 '프롬프트 품질과 응답 품질의 관계 인식', 2),
('11111111-1111-1111-1111-111111111111', 'clarification',
 'AI에게 질문할 때 무엇이 결과에 영향을 준다고 생각하나요?',
 'What do you think affects the results when asking questions to AI?',
 '프롬프트 구성 요소 인식', 3),
('11111111-1111-1111-1111-111111111111', 'clarification',
 '구체적으로 어떤 정보를 추가하면 더 나은 답변을 받을 수 있을까요?',
 'What specific information could you add to get a better answer?',
 '맥락 정보의 중요성 인식', 4),
('11111111-1111-1111-1111-111111111111', 'assumption',
 '왜 그렇게 생각하나요? 다른 가능성은 없을까요?',
 'Why do you think so? Are there no other possibilities?',
 '가정 점검 및 비판적 사고', 5),
('11111111-1111-1111-1111-111111111111', 'consequence',
 '이 프롬프트로 어떤 결과가 나올 것 같나요?',
 'What results do you expect from this prompt?',
 '예측과 실제 비교를 통한 학습', 6),
('11111111-1111-1111-1111-111111111111', 'reflection',
 '복잡한 문제를 "단계별로" 분석해달라고 하면 왜 더 좋은 답이 나올까요?',
 'Why do you get better answers when you ask to analyze complex problems "step by step"?',
 'Chain of Thought 테크닉 인식 유도', 7),

-- Module 2: Few-shot + Output Structuring
('22222222-2222-2222-2222-222222222222', 'exploration',
 '문헌 리뷰할 때 가장 시간이 오래 걸리는 작업은 무엇인가요?',
 'What takes the most time when doing a literature review?',
 '문제 상황 인식', 1),
('22222222-2222-2222-2222-222222222222', 'exploration',
 'AI가 논문을 요약해준다면, 어떤 정보가 포함되어야 유용할까요?',
 'If AI summarizes papers for you, what information should be included to be useful?',
 '출력 형식의 중요성 인식', 2),
('22222222-2222-2222-2222-222222222222', 'clarification',
 '원하는 형식을 AI에게 어떻게 전달하면 좋을까요?',
 'How should you convey the desired format to AI?',
 '출력 구조화 필요성 인식', 3),
('22222222-2222-2222-2222-222222222222', 'reflection',
 '예시를 하나 보여주는 것이 왜 효과적일까요? 몇 개의 예시가 적절할까요?',
 'Why is showing one example effective? How many examples are appropriate?',
 'Few-shot Learning 테크닉 인식 유도', 4),

-- Module 3: CoT + Structuring + Self-Consistency
('33333333-3333-3333-3333-333333333333', 'exploration',
 '좋은 비교 분석에는 어떤 요소가 포함되어야 할까요?',
 'What elements should be included in a good comparative analysis?',
 '분석 프레임워크 인식', 1),
('33333333-3333-3333-3333-333333333333', 'exploration',
 '비교 기준 없이 "비교해줘"라고 하면 어떤 문제가 생길까요?',
 'What problems might arise if you just say "compare" without any criteria?',
 '구조화된 요청의 필요성 인식', 2),
('33333333-3333-3333-3333-333333333333', 'clarification',
 '분석 순서를 명시하면 결과가 어떻게 달라질까요?',
 'How would the results change if you specify the analysis order?',
 '체계적 분석의 가치 인식', 3),
('33333333-3333-3333-3333-333333333333', 'reflection',
 '분석 순서를 미리 알려주는 것과 AI가 알아서 하게 두는 것의 차이는?',
 'What is the difference between specifying the analysis order in advance versus letting AI decide?',
 'Self-Consistency 및 구조화 테크닉 인식 유도', 4),

-- Module 4: Persona + CoT + Few-shot
('44444444-4444-4444-4444-444444444444', 'exploration',
 '데이터를 보여주기만 하면 AI가 당신의 연구 질문을 알 수 있을까요?',
 'Can AI know your research question just by showing the data?',
 '맥락 제공의 중요성 인식', 1),
('44444444-4444-4444-4444-444444444444', 'clarification',
 'AI에게 "전문가" 정체성을 부여하면 어떤 차이가 있을까요?',
 'What difference does it make to give AI an "expert" identity?',
 'Persona 설정의 효과 인식', 2),
('44444444-4444-4444-4444-444444444444', 'assumption',
 '모든 상황에서 전문가 페르소나가 효과적일까요?',
 'Is an expert persona effective in all situations?',
 '테크닉의 적절한 사용 맥락 인식', 3),
('44444444-4444-4444-4444-444444444444', 'reflection',
 'AI에게 전문가 정체성을 부여하면 응답이 어떻게 달라지나요?',
 'How does the response change when you give AI an expert identity?',
 'Persona 테크닉 인식 유도', 4),

-- Module 5: Persona + Few-shot + Constraints
('55555555-5555-5555-5555-555555555555', 'exploration',
 '정책 브리핑과 학술 논문의 문체는 어떻게 다른가요?',
 'How does the writing style differ between a policy briefing and an academic paper?',
 '목적에 따른 문체 차이 인식', 1),
('55555555-5555-5555-5555-555555555555', 'exploration',
 '독자가 누구인지 명시하면 AI 응답이 어떻게 달라질까요?',
 'How does specifying the reader change the AI response?',
 '대상 독자 명시의 중요성 인식', 2),
('55555555-5555-5555-5555-555555555555', 'clarification',
 '분량, 톤, 구성 등의 제약조건을 주면 어떤 효과가 있을까요?',
 'What effect does it have to give constraints like length, tone, and structure?',
 'Constraints 테크닉 인식', 3),
('55555555-5555-5555-5555-555555555555', 'reflection',
 '지금까지 배운 방법들 중 가장 효과적이라고 느낀 것은 무엇인가요?',
 'What method have you found most effective among all that you have learned?',
 '종합 학습 성찰', 4);

-- 4. Resources 시드 데이터
INSERT INTO resources (title, title_en, description, description_en, category, type, url, techniques, order_index) VALUES
-- 테크닉 정리
('Chain of Thought 가이드', 'Chain of Thought Guide',
 '단계별 사고 유도 테크닉 설명. "단계별로 분석해줘"와 같은 프롬프트로 AI가 논리적 사고 과정을 따르도록 유도합니다.',
 'Step-by-step thinking technique explanation. Use prompts like "analyze step by step" to guide AI through logical reasoning.',
 'technique', 'article', '#', ARRAY['Chain of Thought'], 1),
('Few-shot Learning 가이드', 'Few-shot Learning Guide',
 '예시 기반 학습 유도 테크닉. 원하는 출력 형식의 예시를 제공하여 AI가 패턴을 학습하도록 합니다.',
 'Example-based learning technique. Provide examples of desired output format so AI can learn the pattern.',
 'technique', 'article', '#', ARRAY['Few-shot Learning'], 2),
('Persona 설정 가이드', 'Persona Setting Guide',
 '전문가 정체성 부여 테크닉. "당신은 10년 경력의 개발경제학자입니다"와 같이 역할을 부여합니다.',
 'Expert identity assignment technique. Assign roles like "You are a development economist with 10 years of experience".',
 'technique', 'article', '#', ARRAY['Persona'], 3),
('Output Structuring 가이드', 'Output Structuring Guide',
 '출력 형식/구조 명시 테크닉. 표, 목록, 특정 형식 등 원하는 출력 구조를 명확히 지정합니다.',
 'Output format specification technique. Clearly specify desired output structure like tables, lists, or specific formats.',
 'technique', 'article', '#', ARRAY['Output Structuring'], 4),
('Constraints 가이드', 'Constraints Guide',
 '제약 조건 설정 테크닉. 분량, 톤, 대상 독자, 금지 사항 등 제약조건을 명시합니다.',
 'Constraint setting technique. Specify constraints like length, tone, target audience, and restrictions.',
 'technique', 'article', '#', ARRAY['Constraints'], 5),

-- 공식 가이드
('Anthropic Prompt Engineering Guide', 'Anthropic Prompt Engineering Guide',
 'Claude 공식 프롬프트 엔지니어링 가이드. Anthropic에서 제공하는 최신 프롬프트 작성 기법을 배울 수 있습니다.',
 'Official Claude prompt engineering guide. Learn the latest prompt writing techniques from Anthropic.',
 'guide', 'document', 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview', ARRAY[]::TEXT[], 1),
('OpenAI Prompt Engineering Guide', 'OpenAI Prompt Engineering Guide',
 'OpenAI 공식 프롬프트 가이드. GPT 모델을 위한 프롬프트 작성 모범 사례를 제공합니다.',
 'Official OpenAI prompt guide. Provides best practices for writing prompts for GPT models.',
 'guide', 'document', 'https://platform.openai.com/docs/guides/prompt-engineering', ARRAY[]::TEXT[], 2),
('DAIR.AI Prompt Engineering Guide', 'DAIR.AI Prompt Engineering Guide (Korean)',
 '한국어 프롬프트 엔지니어링 가이드. 다양한 프롬프트 기법을 한국어로 상세히 설명합니다.',
 'Korean prompt engineering guide. Explains various prompt techniques in detail in Korean.',
 'guide', 'document', 'https://www.promptingguide.ai/kr', ARRAY[]::TEXT[], 3),
('Learn Prompting', 'Learn Prompting',
 '프롬프트 엔지니어링 종합 학습 사이트. 기초부터 고급 기법까지 체계적으로 배울 수 있습니다.',
 'Comprehensive prompt engineering learning site. Learn systematically from basics to advanced techniques.',
 'guide', 'document', 'https://learnprompting.org', ARRAY[]::TEXT[], 4),

-- 추천 영상
('Anthropic YouTube 채널', 'Anthropic YouTube Channel',
 'Claude 공식 튜토리얼. Anthropic에서 제공하는 Claude 활용 영상을 시청할 수 있습니다.',
 'Official Claude tutorials. Watch Claude usage videos provided by Anthropic.',
 'video', 'video', 'https://www.youtube.com/@anthropic-ai', ARRAY[]::TEXT[], 1),
('AI Jason 채널', 'AI Jason Channel',
 '실용적 프롬프트 팁. 실무에서 바로 활용할 수 있는 프롬프트 기법을 배울 수 있습니다.',
 'Practical prompt tips. Learn prompt techniques that can be immediately applied in practice.',
 'video', 'video', 'https://www.youtube.com/@AIJasonZ', ARRAY[]::TEXT[], 2),
('All About AI', 'All About AI',
 '상세한 테크닉 설명. 프롬프트 엔지니어링 테크닉을 깊이 있게 설명하는 채널입니다.',
 'Detailed technique explanations. A channel that explains prompt engineering techniques in depth.',
 'video', 'video', 'https://www.youtube.com/@AllAboutAI', ARRAY[]::TEXT[], 3),

-- 심화 학습
('DeepLearning.AI 프롬프트 코스', 'DeepLearning.AI Prompt Course',
 'ChatGPT 프롬프트 엔지니어링 무료 코스. Andrew Ng과 OpenAI가 함께 만든 체계적인 코스입니다.',
 'Free ChatGPT prompt engineering course. A systematic course created by Andrew Ng and OpenAI.',
 'advanced', 'course', 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/', ARRAY[]::TEXT[], 1),
('Chain-of-Thought 논문', 'Chain-of-Thought Paper',
 'CoT 기법 원본 학술 논문. Chain of Thought Prompting 기법의 이론적 배경을 이해할 수 있습니다.',
 'Original CoT technique academic paper. Understand the theoretical background of Chain of Thought Prompting.',
 'advanced', 'document', 'https://arxiv.org/abs/2201.11903', ARRAY['Chain of Thought'], 2);
